[package]
name = "builder"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = { version = "0.11.15", features = ["uefi"] }
kernel = { path = "../kernel", artifact = "bin", target = "x86_64-unknown-none" }
